config:
  cookie: ...
  x_csrf_token: ...

  groups:
    свет 1:
      - mix: [весь свет, на кухне]
      - mix:
        - [свет, люстра]
        - на кухне
      - mix:
        - подсветка
        - на кухне

    свет 2:
      - mix:
        - подсветка
        - на кухне

  scenarios:
    - name:
        - compile:
            phrase: включи
            postfix: свет
      actions:
        Алиса: Алиса, повтори за мной "Что именно включить?"
    
    - name:
        - compile:
            phrase: выключи
            postfix: свет
      actions:
        Алиса: Алиса, повтори за мной "Что именно выключить?"

    - name:
        - combine:
          - [убери, уберись]
          - в спальне
      actions:
        Пылесос спальня: true
        Алиса: Алиса, повтори за мной "Начинаю уборку в спальне"